FROM node:18.15.0-alpine AS builder

WORKDIR /app

COPY server/package.json server/package.json
COPY portal/package.json portal/package.json
COPY package*.json .
RUN npm ci

COPY . .
RUN npx prisma generate --schema=./server/prisma/schema.prisma
RUN npm run build:server

FROM node:18.15.0-alpine

WORKDIR /app

COPY server/package.json package.json
RUN npm install --omit=dev
COPY server/prisma prisma
RUN npx prisma generate

COPY --from=builder /app/server/dist .
CMD [ "node", "index.js" ]
