name: CI/CD

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

  pull_request:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  test-portal:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - run: npm ci
      - run: make init-prisma
      - run: npm run ci:portal
        if: ${{ !cancelled() }}

  test-server:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - run: npm ci
      - run: make init-prisma
      - run: npm run ci:server
        if: ${{ !cancelled() }}

  test-worker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
      - run: npm ci
      - run: make init-prisma
      - run: npm run ci:worker
        if: ${{ !cancelled() }}

  build:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    needs: [test-server, test-portal, test-worker]

    strategy:
      matrix:
        component:
          - portal
          - server
          - worker

    steps:
      - uses: actions/checkout@v3
      - name: Generate image tag
        run: echo "IMAGE_TAG=`git rev-parse --short=7 HEAD`" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.${{ matrix.component }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uenroll-${{ matrix.component }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/uenroll-${{ matrix.component }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    needs: [test-server, test-portal, test-worker, build]
    steps:
      - uses: actions/checkout@v3
      - name: Generate image tag
        run: echo "IMAGE_TAG=`git rev-parse --short=7 HEAD`" >> $GITHUB_ENV
      - uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_SERVER }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - uses: azure/k8s-deploy@v4
        with:
          namespace: uenroll
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/ingress.yaml
            kubernetes/service.yaml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uenroll-server:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/uenroll-portal:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/uenroll-worker:${{ env.IMAGE_TAG }}
